# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_controller(object):
    def setupUi(self, controller):
        controller.setObjectName("controller")
        controller.resize(799, 382)
        font = QtGui.QFont()
        font.setPointSize(9)
        controller.setFont(font)
        controller.setTabletTracking(False)
        self.centralwidget = QtWidgets.QWidget(controller)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(143, 41, 36, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(390, 30, 21, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(580, 30, 21, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(530, 30, 36, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(143, 101, 36, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(143, 161, 36, 16))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(143, 221, 36, 16))
        self.label_8.setObjectName("label_8")
        self.lineEditxxy_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditxxy_12.setGeometry(QtCore.QRect(420, 30, 101, 24))
        self.lineEditxxy_12.setText("")
        self.lineEditxxy_12.setObjectName("lineEditxxy_12")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(234, 102, 40, 24))
        self.pushButton_22.setTabletTracking(False)
        self.pushButton_22.setStyleSheet("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(280, 102, 40, 24))
        self.pushButton_23.setTabletTracking(False)
        self.pushButton_23.setStyleSheet("")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(187, 102, 41, 24))
        self.pushButton_21.setTabletTracking(False)
        self.pushButton_21.setStyleSheet("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(326, 102, 40, 24))
        self.pushButton_24.setTabletTracking(False)
        self.pushButton_24.setStyleSheet("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_32 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_32.setGeometry(QtCore.QRect(234, 162, 40, 24))
        self.pushButton_32.setTabletTracking(False)
        self.pushButton_32.setStyleSheet("")
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_33.setGeometry(QtCore.QRect(280, 162, 40, 24))
        self.pushButton_33.setTabletTracking(False)
        self.pushButton_33.setStyleSheet("")
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_31.setGeometry(QtCore.QRect(187, 162, 41, 24))
        self.pushButton_31.setTabletTracking(False)
        self.pushButton_31.setStyleSheet("")
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_34 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_34.setGeometry(QtCore.QRect(326, 162, 40, 24))
        self.pushButton_34.setTabletTracking(False)
        self.pushButton_34.setStyleSheet("")
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_42 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_42.setGeometry(QtCore.QRect(234, 222, 40, 24))
        self.pushButton_42.setTabletTracking(False)
        self.pushButton_42.setStyleSheet("")
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_43 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_43.setGeometry(QtCore.QRect(280, 222, 40, 24))
        self.pushButton_43.setTabletTracking(False)
        self.pushButton_43.setStyleSheet("")
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_41 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_41.setGeometry(QtCore.QRect(187, 222, 41, 24))
        self.pushButton_41.setTabletTracking(False)
        self.pushButton_41.setStyleSheet("")
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_44 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_44.setGeometry(QtCore.QRect(326, 222, 40, 24))
        self.pushButton_44.setTabletTracking(False)
        self.pushButton_44.setStyleSheet("")
        self.pushButton_44.setObjectName("pushButton_44")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(530, 100, 36, 21))
        self.label_10.setObjectName("label_10")
        self.lineEditxxy_22 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditxxy_22.setGeometry(QtCore.QRect(420, 100, 101, 24))
        self.lineEditxxy_22.setText("")
        self.lineEditxxy_22.setObjectName("lineEditxxy_22")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(580, 100, 21, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(390, 100, 21, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName("pushButton_25")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(530, 160, 36, 21))
        self.label_11.setObjectName("label_11")
        self.lineEditxxy_32 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditxxy_32.setGeometry(QtCore.QRect(420, 160, 101, 24))
        self.lineEditxxy_32.setText("")
        self.lineEditxxy_32.setObjectName("lineEditxxy_32")
        self.pushButton_36 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_36.setGeometry(QtCore.QRect(580, 160, 21, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_35 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_35.setGeometry(QtCore.QRect(390, 160, 21, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setObjectName("pushButton_35")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(530, 220, 36, 21))
        self.label_12.setObjectName("label_12")
        self.lineEditxxy_42 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditxxy_42.setGeometry(QtCore.QRect(420, 220, 101, 24))
        self.lineEditxxy_42.setText("")
        self.lineEditxxy_42.setObjectName("lineEditxxy_42")
        self.pushButton_46 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_46.setGeometry(QtCore.QRect(580, 220, 21, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_46.setFont(font)
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_45 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_45.setGeometry(QtCore.QRect(390, 220, 21, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_45.setFont(font)
        self.pushButton_45.setObjectName("pushButton_45")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(620, 30, 171, 221))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_refresh.setGeometry(QtCore.QRect(30, 280, 80, 24))
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.lineEditxxy_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditxxy_11.setGeometry(QtCore.QRect(90, 40, 51, 21))
        self.lineEditxxy_11.setObjectName("lineEditxxy_11")
        self.lineEditxxy_21 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditxxy_21.setGeometry(QtCore.QRect(90, 100, 51, 21))
        self.lineEditxxy_21.setObjectName("lineEditxxy_21")
        self.lineEditxxy_31 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditxxy_31.setGeometry(QtCore.QRect(90, 160, 51, 21))
        self.lineEditxxy_31.setObjectName("lineEditxxy_31")
        self.lineEditxxy_41 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditxxy_41.setGeometry(QtCore.QRect(90, 220, 51, 21))
        self.lineEditxxy_41.setObjectName("lineEditxxy_41")
        self.lineEditxxy_imformation = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditxxy_imformation.setGeometry(QtCore.QRect(210, 270, 161, 24))
        self.lineEditxxy_imformation.setObjectName("lineEditxxy_imformation")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(187, 40, 41, 24))
        self.pushButton_11.setTabletTracking(False)
        self.pushButton_11.setStyleSheet("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(234, 40, 40, 24))
        self.pushButton_12.setTabletTracking(False)
        self.pushButton_12.setStyleSheet("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(326, 40, 40, 24))
        self.pushButton_14.setTabletTracking(False)
        self.pushButton_14.setStyleSheet("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(280, 40, 40, 24))
        self.pushButton_13.setTabletTracking(False)
        self.pushButton_13.setStyleSheet("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_concect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_concect.setGeometry(QtCore.QRect(430, 280, 75, 23))
        self.pushButton_concect.setObjectName("pushButton_concect")
        self.pushButton_disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_disconnect.setGeometry(QtCore.QRect(540, 280, 75, 23))
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 61, 20))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 61, 20))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 160, 61, 20))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 220, 61, 20))
        self.label_9.setObjectName("label_9")
        controller.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(controller)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        controller.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(controller)
        self.statusbar.setObjectName("statusbar")
        controller.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(controller)
        self.toolBar.setObjectName("toolBar")
        controller.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(controller)
        QtCore.QMetaObject.connectSlotsByName(controller)

    def retranslateUi(self, controller):
        _translate = QtCore.QCoreApplication.translate
        controller.setWindowTitle(_translate("controller", "MainWindow"))
        controller.setToolTip(_translate("controller", "<html><head/><body><p>0.0</p></body></html>"))
        self.label_2.setText(_translate("controller", "degree"))
        self.pushButton_19.setToolTip(_translate("controller", "<html><head/><body><p>smaller</p></body></html>"))
        self.pushButton_19.setText(_translate("controller", "<"))
        self.pushButton_20.setToolTip(_translate("controller", "<html><head/><body><p>bigger</p></body></html>"))
        self.pushButton_20.setText(_translate("controller", ">"))
        self.label_3.setText(_translate("controller", "degree"))
        self.label_4.setText(_translate("controller", "degree"))
        self.label_6.setText(_translate("controller", "mm"))
        self.label_8.setText(_translate("controller", "mm"))
        self.lineEditxxy_12.setToolTip(_translate("controller", "<html><head/><body><p>how much will move</p></body></html>"))
        self.pushButton_22.setToolTip(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_22.setWhatsThis(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_22.setText(_translate("controller", "stop"))
        self.pushButton_23.setToolTip(_translate("controller", "<html><head/><body><p>Move to the 0 position</p></body></html>"))
        self.pushButton_23.setWhatsThis(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_23.setText(_translate("controller", "to 0"))
        self.pushButton_21.setToolTip(_translate("controller", "<html><head/><body><p>Move to the machine origin</p></body></html>"))
        self.pushButton_21.setWhatsThis(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_21.setText(_translate("controller", "home"))
        self.pushButton_24.setToolTip(_translate("controller", "<html><head/><body><p>Set the current position to zero</p></body></html>"))
        self.pushButton_24.setWhatsThis(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_24.setText(_translate("controller", "0 set"))
        self.pushButton_32.setToolTip(_translate("controller", "<html><head/><body><p>stoop move</p></body></html>"))
        self.pushButton_32.setWhatsThis(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_32.setText(_translate("controller", "stop"))
        self.pushButton_33.setToolTip(_translate("controller", "<html><head/><body><p>Move to the 0 position</p></body></html>"))
        self.pushButton_33.setWhatsThis(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_33.setText(_translate("controller", "to 0"))
        self.pushButton_31.setToolTip(_translate("controller", "<html><head/><body><p>Move to the machine origin</p></body></html>"))
        self.pushButton_31.setWhatsThis(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_31.setText(_translate("controller", "home"))
        self.pushButton_34.setToolTip(_translate("controller", "<html><head/><body><p>Set the current position to zero</p></body></html>"))
        self.pushButton_34.setWhatsThis(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_34.setText(_translate("controller", "0 set"))
        self.pushButton_42.setToolTip(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_42.setWhatsThis(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_42.setText(_translate("controller", "stop"))
        self.pushButton_43.setToolTip(_translate("controller", "<html><head/><body><p>Move to the 0 position</p></body></html>"))
        self.pushButton_43.setWhatsThis(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_43.setText(_translate("controller", "to 0"))
        self.pushButton_41.setToolTip(_translate("controller", "<html><head/><body><p>Move to the machine origin</p></body></html>"))
        self.pushButton_41.setWhatsThis(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_41.setText(_translate("controller", "home"))
        self.pushButton_44.setToolTip(_translate("controller", "<html><head/><body><p>Set the current position to zero</p></body></html>"))
        self.pushButton_44.setWhatsThis(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_44.setText(_translate("controller", "0 set"))
        self.label_10.setText(_translate("controller", "degree"))
        self.lineEditxxy_22.setToolTip(_translate("controller", "<html><head/><body><p>how much will move</p></body></html>"))
        self.pushButton_26.setToolTip(_translate("controller", "<html><head/><body><p>bigger</p></body></html>"))
        self.pushButton_26.setText(_translate("controller", ">"))
        self.pushButton_25.setToolTip(_translate("controller", "<html><head/><body><p>smaller</p></body></html>"))
        self.pushButton_25.setText(_translate("controller", "<"))
        self.label_11.setText(_translate("controller", "mm"))
        self.lineEditxxy_32.setToolTip(_translate("controller", "<html><head/><body><p>how much will move</p></body></html>"))
        self.pushButton_36.setToolTip(_translate("controller", "<html><head/><body><p>bigger</p></body></html>"))
        self.pushButton_36.setText(_translate("controller", ">"))
        self.pushButton_35.setToolTip(_translate("controller", "<html><head/><body><p>smaller</p></body></html>"))
        self.pushButton_35.setText(_translate("controller", "<"))
        self.label_12.setText(_translate("controller", "mm"))
        self.lineEditxxy_42.setToolTip(_translate("controller", "<html><head/><body><p>how much will move</p></body></html>"))
        self.pushButton_46.setToolTip(_translate("controller", "<html><head/><body><p>bigger</p></body></html>"))
        self.pushButton_46.setText(_translate("controller", ">"))
        self.pushButton_45.setToolTip(_translate("controller", "<html><head/><body><p>smaller</p></body></html>"))
        self.pushButton_45.setText(_translate("controller", "<"))
        self.graphicsView.setToolTip(_translate("controller", "<html><head/><body><p>the synchro optical image</p></body></html>"))
        self.pushButton_refresh.setToolTip(_translate("controller", "<html><head/><body><p>refresh all data</p></body></html>"))
        self.pushButton_refresh.setText(_translate("controller", "refresh"))
        self.pushButton_11.setToolTip(_translate("controller", "<html><head/><body><p>Move to the machine origin</p></body></html>"))
        self.pushButton_11.setWhatsThis(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_11.setText(_translate("controller", "home"))
        self.pushButton_12.setToolTip(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_12.setWhatsThis(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_12.setText(_translate("controller", "stop"))
        self.pushButton_14.setToolTip(_translate("controller", "<html><head/><body><p>Set the current position to zero</p></body></html>"))
        self.pushButton_14.setWhatsThis(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_14.setText(_translate("controller", "0 set"))
        self.pushButton_13.setToolTip(_translate("controller", "<html><head/><body><p>Move to the 0 position</p></body></html>"))
        self.pushButton_13.setWhatsThis(_translate("controller", "<html><head/><body><p>stop move</p></body></html>"))
        self.pushButton_13.setText(_translate("controller", "to 0"))
        self.pushButton_concect.setText(_translate("controller", "connect"))
        self.pushButton_disconnect.setText(_translate("controller", "disconnect"))
        self.label.setText(_translate("controller", "rotate"))
        self.label_5.setText(_translate("controller", "pitch"))
        self.label_7.setText(_translate("controller", "longitudinal"))
        self.label_9.setText(_translate("controller", "horizontal"))
        self.toolBar.setWindowTitle(_translate("controller", "toolBar"))
